### ISSUE TITLE
Would I get pushed back by Apple and Google if I wrap a website?

### ISSUE THREAD

**Issue by johnRivs** [jasonelle-archive/jasonelle-v2#102]
I came across [this](https://www.freecodecamp.org/news/how-to-turn-your-website-into-a-mobile-app-with-7-lines-of-json-631c9c9895f5/) and thought I could use this to build an app that simply shows a website. I suspect this wouldn't really fly by store policies, right? Cause one day I submit something, gets approved and the next day I make the website show something completely different without telling Apple/Google.

Could anybody using Jasonette for this purpose share their experience when trying to publish the app?

**Comment by clsource** [comment]
Yes Apple is stricter than Google regarding App Submissions.
You can have your app rejected if this only was a mere Website in an WebKit Wrapper.

Apple allows apps made enterily with Web Technologies, but this app must have more than just a few links and images to be considered "AppStore worthy".

If you change the app "too much" for whats was sent to review, you risk of you account being banned from Apple. So be aware of changes too far away of what was sent before.
