### ISSUE TITLE
iOS App not accepted by App Store Connect

### ISSUE THREAD

**Issue by jstorq** [jasonelle-archive/jasonelle-v2#108]
Hi there.  I just attempted to upload my iOS app built with xCode from JSONETTE-iOS-master to App Store Connect and the app was rejected.  Following is the contents of the email.  Evidently the use of UIWebView is no longer acceptable.  Do you have a fix for this and any recommendations?  (Do I just go swap out UIWebView with WKWebView and that's that?)

Thanks.

-----------------

Dear Developer,

We identified one or more issues with a recent delivery for your app, "Divinaetion" 1.0 (1). Please correct the following issues, then upload again.ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).
--

**Comment by clsource** [comment]
hi, thanks for this report
please use the latest develop version. UIWebview was removed a long time ago.

https://github.com/jasonelle/jasonette-ios

thanks

**Comment by jstorq** [comment]
Thanks for the feedback.  Unfortunately I clone git@github.com:jasonelle/jasonette-ios.git and tried to build it and there are two build errors.  Both on the develop and master branch.  Is there something I'm missing?  Are you able to clone the branch, open in XCode and build without error?  Thanks.

**Comment by clsource** [comment]
Please open a new Issue with the details of the error :)
