### ISSUE TITLE
Cannot Run Default App on iOS

### ISSUE THREAD

**Issue by tejt99** [jasonelle-archive/jasonelle-v2#111]
Hi, I'm new to iOS development and thought i'd try out Jasonelle/Jasonette instead of learning swift but I downloaded the `jasonette-ios-master`, changed a word on `bundle identifier` and ran it.

I immediately recieved an error of:

> *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'

I really hope that this can be resolved because jasonette seems like such a great rescource.

Thanks

**Comment by clsource** [comment]
Hello this is probably due to using an older version.

please check that you are using the latest develop branch in 
https://github.com/jasonelle/jasonette-ios
