### ISSUE TITLE
Getting error saying 'SocketRocket/SocketRocket.h' file not found

### ISSUE THREAD

**Issue by mghatiya** [jasonelle-archive/jasonelle-v2#119]
Hi,

My Jasonette app is building fine for the simulators, but when I change the target to "Any iOS Device (arm64, armv7)", I am getting a build error saying "'SocketRocket/SocketRocket.h' file not found"

Here's how it looks.

![Screenshot 2022-01-30 at 1 41 14 AM](https://user-images.githubusercontent.com/35567433/151676128-f41314db-728e-4b5f-bab2-674c66680a1d.png)

Any suggestions on how to fix this error?

Thanks,
Mukesh

**Comment by clsource** [comment]
Normally this is fixed by doing a `pod install` command.
Also check that you are using a paid developer account for building for real devices.
Apple I think does not allows external frameworks in free accounts as far as I know

**Comment by ShonFrazier** [comment]
`pod install` and open the `xcworkspace` rather than the `xcodeproj`

**Comment by mghatiya** [comment]
Thanks. Not sure what all I did now. The issue had got fixed.
