### ISSUE TITLE
Unable to get input field default value

### ISSUE THREAD

**Issue by Pvybhav** [jasonelle-archive/jasonelle-v2#12]
![input issue2](https://user-images.githubusercontent.com/22319118/49132573-ead34a80-f302-11e8-890c-96dda0c100bb.png)
![input issue](https://user-images.githubusercontent.com/22319118/49132575-ead34a80-f302-11e8-8ddb-a26fd589f31e.png)
I am getting {{$get.name_of_the_inputfield}}, while trying to save the todo - input default value to global varaibles

Mobile Model : Nokia-6
OS: Android - Oreo(8.1)

**Comment by Pvybhav** [comment]
Reference: https://github.com/jasonelle/docs/tree/develop/examples/jasonette/apps/todo-app

**Comment by clsource** [comment]
Hello, the example in the docs has an outdated url. Now it should work fine.
Thank you for pointing that out.
