### ISSUE TITLE
Git documentation link broken

### ISSUE THREAD

**Issue by christianswanepoel** [jasonelle-archive/jasonelle-v2#16]
The links on the project page for iOS / Android are broken. I am guessing I should still use Jasonette links?
i.e. the link "Jasonette Android" and "Jasonette iOS" on https://github.com/jasonelle/jasonelle should link to "https://github.com/jasonelle/jasonette-ios" and "https://github.com/jasonelle/jasonette-android" respectively?

**Comment by clsource** [comment]
Hello, 
yes the website and documentation pages are still a work in progress.
So maybe some links are broken.

If you need to download the latest version you can go here

https://github.com/jasonelle/jasonelle/releases

👍 
thanks.

**Comment by christianswanepoel** [comment]
Hey
I did a git clone from https://github.com/jasonelle/jasonette-ios - should
I rather use the link you sent?

**Comment by clsource** [comment]
Well that repo contains the latest code too. You can use that if you want :)
