### ISSUE TITLE
Intent for external URL's

### ISSUE THREAD

**Issue by idimeca** [jasonelle-archive/jasonelle-v2#22]
Hi,

I have been using Jasonette to create an app for my website. Using it as a web container background.

I am stuck at creating an intent to open external url's of my website in the default android browser or if an app exists with the default app. Like, the link that points to my twitter account should open a choice window for the visitor to choose the app or browser to open the link.

This is my first app so I am not very experienced and I have tried many advices online with no result.

Any help would be appreciated.

Thanks,
Idi

**Comment by christianswanepoel** [comment]
Hi I actually worked through the same issue today. The following works for me.
https://www.jasonbase.com/things/PlE7.json

It basically looks for any pages not part of the main domain and opens it in a web browser. Works for both iOS and Android.

Enjoy!

**Comment by idimeca** [comment]
Hi Christian,

Great solution, thanks for sharing.

Cheers,
Idi

**Comment by idimeca** [comment]
In iOS, the app presents a  blank page instead of the previous url view when you click the Done button after you opened the external URL. Did you face this issue? Probably we need something like onBackPressed for android.

Idi

**Comment by christianswanepoel** [comment]
My JSON example above works perfectly, for me at least, in both iOS and Android. My iOS code is unchanged, but I added your fix, from ticket #13 for the “back button” to function correctly in Android. 

Maybe load my basic JSON again and see if you still seeing a blank screen when clicking on back? I found that sometimes the JSON is technically the same but it works on one OS and not on another, then going back to basics “fixes” the issue (not sure why).

**Comment by idimeca** [comment]
Yeah, I had a mistake in my json file by adding and id to the body which caused the issue. Now it's set.

Thanks,
Idi

**Comment by clsource** [comment]
> Hi I actually worked through the same issue today. The following works for me.
> https://www.jasonbase.com/things/PlE7.json
> 
> It basically looks for any pages not part of the main domain and opens it in a web browser. Works for both iOS and Android.
> 
> Enjoy!

Please @christianswanepoel share your code here since jasonbase is down. 
Thanks 👍

**Comment by christianswanepoel** [comment]
See code sample previously referenced:

```
{
    "$jason": {
        "head": {
            "title": "External - Links",
            "description": "Opens tab if external link",
            "actions": {
                "handleLink": [
                    {
                        "{{#if $jason.url.indexOf('google') == -1 }}": {
                            "type": "$href",
                            "options": {
                                "url": "{{$jason.url}}",
                                "view": "web"
                            }
                        }
                    },
                    {
                       "{{#else}}": {
                           "type": "$default"
                       }
                    }
                ]
             }
        },
        "body": {
            "background": {
                "type": "html",
                "url": "https://www.google.com",
                "action": {
                    "trigger": "handleLink"
                }
            }
        }
    }
}
```

**Comment by clsource** [comment]
Thanks 👍

**Comment by najmuzzaman-mohammad** [comment]
> See code sample previously referenced:
> 
> ```
> {
>     "$jason": {
>         "head": {
>             "title": "External - Links",
>             "description": "Opens tab if external link",
>             "actions": {
>                 "handleLink": [
>                     {
>                         "{{#if $jason.url.indexOf('google') == -1 }}": {
>                             "type": "$href",
>                             "options": {
>                                 "url": "{{$jason.url}}",
>                                 "view": "web"
>                             }
>                         }
>                     },
>                     {
>                        "{{#else}}": {
>                            "type": "$default"
>                        }
>                     }
>                 ]
>              }
>         },
>         "body": {
>             "background": {
>                 "type": "html",
>                 "url": "https://www.google.com",
>                 "action": {
>                     "trigger": "handleLink"
>                 }
>             }
>         }
>     }
> }
> ```

I am getting the following error while trying to use this:
2019-09-18 15:01:17.730 4238-4633/com.jasonette W/JasonParser: processTask : java.lang.NullPointerException: Attempt to invoke virtual method 'com.eclipsesource.v8.V8Locker com.eclipsesource.v8.V8.getLocker()' on a null object reference

**Comment by christianswanepoel** [comment]
I just checked, mine still works - all I have extra is a header in the body...
`{
    "$jason": {
        "head": {
            "title": "External - Links",
            "description": "Opens tab if external link"
            "actions": {
                "handleLink": [
                    {
                        "{{#if $jason.url.indexOf('google') == -1 }}": {
                            "type": "$href",
                            "options": {
                                "url": "{{$jason.url}}",
                                "view": "web"
                            }
                        }
                    },
                    {
                       "{{#else}}": {
                           "type": "$default"
                       }
                    }
                ]
             }
        },
        "body": {
            "header": { 
                "title": {
                    "type": "image",
                    "url": "https://raw.githubusercontent.com/jasonelle/docs/develop/examples/jasonette/apps/jason-app/images/qr-code.png",
                    "style": {
                        "width": "160",
                        "height": "13"
                    }
                },
                "style": {
                    "background": "rgb(0,121,255)",
                    "padding": "10",
                    "color": "#ffffff"
                }
            },
            "background": {
                "type": "html",
                "url": "https://google.com",
                "action": {
                    "trigger": "handleLink"
                }
            }
        }
    }
}
`

**Comment by najmuzzaman-mohammad** [comment]
> I just checked, mine still works - all I have extra is a header in the body...
> `{ "$jason": { "head": { "title": "External - Links", "description": "Opens tab if external link" "actions": { "handleLink": [ { "{{#if $jason.url.indexOf('google') == -1 }}": { "type": "$href", "options": { "url": "{{$jason.url}}", "view": "web" } } }, { "{{#else}}": { "type": "$default" } } ] } }, "body": { "header": { "title": { "type": "image", "url": "https://raw.githubusercontent.com/jasonelle/docs/develop/examples/jasonette/apps/jason-app/images/qr-code.png", "style": { "width": "160", "height": "13" } }, "style": { "background": "rgb(0,121,255)", "padding": "10", "color": "#ffffff" } }, "background": { "type": "html", "url": "https://google.com", "action": { "trigger": "handleLink" } } } } } `

found the issue. for some reason, the error shows up only in Android Studio's debug mode. Generating an APK and installing that works perfectly. Thanks :)

**Comment by haydentech** [comment]
I'm having the same null pointer issue as @mohammadnajmuzzaman.  I'm glad there's a workaround via using the apk, but it stinks to not be able to use the built-in debugger.
