### ISSUE TITLE
Progress bars and spinners

### ISSUE THREAD

**Issue by christianswanepoel** [jasonelle-archive/jasonelle-v2#23]
Is there a way to insert a progress bar or spinner on "long" page loads?
e.g. there's a second or more delay after clicking on a link to open "view": "web" and the device taking action.

This only happens on sites that take a while to respond (i.e the sample link below will open instantly)

sample: https://www.jasonbase.com/things/87Md.json

**Comment by idimeca** [comment]
Doesn't this help? https://docs.jasonette.com/href/#preload

**Comment by christianswanepoel** [comment]
> Doesn't this help? https://docs.jasonette.com/href/#preload

It makes sense but I am having difficulty implementing it in the following context.
https://www.jasonbase.com/things/87Md.json

**Comment by idimeca** [comment]
haven't tested it but logically should go like this

"handleLink": [
          {
            "{{#if $jason.url.indexOf('google') == -1 }}": {
              "type": "$href",
              "options": {
                "url": "{{$jason.url}}",
                "view": "web",
"preload": { "style": { "background": "#ff0000" }, "layers": [{ "type": "image", "url": "file://loading.gif", "style": { "top": "50%-25", "left": "50%-25", "width": "50", "height": "50" } }] }
              }
            }
          },

**Comment by christianswanepoel** [comment]
I made the changes, slowed down my device connection to simulate 64kbits and still don't see any difference. I tested it on both Android and iOS. :(

Updated JSON: https://www.jasonbase.com/things/4jxY.json

**Comment by clsource** [comment]
@christianswanepoel please paste the json here so I can have a look 👍 
thanks.
