### ISSUE TITLE
getUsermedia with jasonelle/jasonette?

### ISSUE THREAD

**Issue by veglinus** [jasonelle-archive/jasonelle-v2#24]
Hiya, has anyone had any luck getting getUserMedia to work within a jasonette/jasonelle app? My site uses getUsermedia to access the users camera to read data.
Doesn't work on either iOS or android, I suspect I have to do some more configuring but I need some help on what I should try doing.

Android error says: NotAllowedError: Permission Denied
iOS: getUsermedia is not defined

Does it have anything to do with setting permissions to allow camera access or is it just not possible to do? I've tried playing around with permissions but as I'm not very experienced building apps I'm having a hard time.

As a sidenote my website is using QuaggaJS as a barcode scanner, I don't want to use the $vision api included because my setup is working pretty well right now and I want it to work/look the same as much as possible across all platforms. If I don't a solution I'll probably go down that route though.

Any tips or suggestions would be greatly appreciated.
Thank you!

**Comment by christianswanepoel** [comment]
I might be wrong but won't it be easier to use Jasonelle's native access to the camera in your app?
e.g. 
```
{
  "$jason": {
    "body": {
      "background": "camera"
    }
  }
}
```

See link (even includes barcode scanner example): https://docs.jasonette.com/actions/#mediacamera

**Comment by veglinus** [comment]
> I might be wrong but won't it be easier to use Jasonelle's native access to the camera in your app?
> e.g.
> 
> ```
> {
>   "$jason": {
>     "body": {
>       "background": "camera"
>     }
>   }
> }
> ```
> See link (even includes barcode scanner example): https://docs.jasonette.com/actions/#mediacamera

Don't think that would work. My web app uses getUserMedia for the scanning functionality, don't think I can hand it Jasonelle's camera feed. I'm using this barcode scanner: https://serratus.github.io/quaggaJS/

**Comment by christianswanepoel** [comment]
The jasonbase link below is able to load the quaggaJS demo page without error, however the camera is off (guessing a permissions issue) - https://www.jasonbase.com/things/bMgx/edit

The same quaggaJS demo page is however loadable in my phone's onboard browser, again pointing to a App permissions issue. Maybe read. https://developer.android.com/guide/topics/media/camera

**Comment by veglinus** [comment]
I'm playing around a bit with android permissions now, by inserting this code in the AndroidManifest.xml:
`
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" android:required="true" />
    <uses-feature android:name="android.hardware.camera.level.full" />
`
and then manually enabling the permissions in the settings. Still no luck, but as previously mentioned it's probably related to permission yeah.

**Comment by nspebi** [comment]
This'll be my first github comment so go easy on me.

I realize that this issue has been closed but I'd like to share my experiences trying (and failing) to implement quaggaJS into my Jasonette project.

To me it seems as though Jasonette on iOS doesn't support WebRTC, specifically getUserMedia. As stated above by @veglinus, the function is undefined.

WebRTC provides a polyfill<sup>[1](https://www.npmjs.com/package/webrtc-adapter)</sup> for getUserMedia, yet as far as I can tell it doesn't work with Jasonette, either.

All my testing was done on iOS so I can't make any claims that this is relevant for Android.

I would greatly appreciate if somebody more knowledgeable than I could take a look at WebRTC support for Jasonette iOS. Is there a way to implement support for getUserMedia or is it principally too big of a task?

---
References

1: https://www.npmjs.com/package/webrtc-adapter

**Comment by clsource** [comment]
I believe the issue is because Apple Still not supports getUserMedia

https://stackoverflow.com/questions/29160819/how-to-use-getusermedia-in-chrome-for-ios/45454817

https://github.com/webrtc/samples/issues/933

http://iswebrtcreadyyet.com/
