### ISSUE TITLE
Extend preload timing to prevent white screen on startup

### ISSUE THREAD

**Issue by idimeca** [jasonelle-archive/jasonelle-v2#25]
When the app launches initially there's a white screen before preload.json kicks in.

Anyone knows how to add preload.json as windowBackground as well. I think that should be the way to go with this.

Thanks,
Idi

**Comment by idimeca** [comment]
I solved this by adding a drawable file in android and disabling preload in launch in android.

In iOS simply by disabling preload and using the default LaunchScreen storyboard.

**Comment by clsource** [comment]
thanks
