### ISSUE TITLE
Target "_blank" links not opening in iOS

### ISSUE THREAD

**Issue by idimeca** [jasonelle-archive/jasonelle-v2#26]
In the background web container which uses WKWebView, links with target "_blank" are not clickable. This seems a known issue in iOS.

There's a solution here https://stackoverflow.com/questions/25713069/why-is-wkwebview-not-opening-links-with-target-blank but not sure how to implement it. It would be great if a developer could chip in.

Another way around is to load a script like this
`var allLinks = document.getElementsByTagName('a');if (allLinks) { var i;for (i=0; i<allLinks.length; i++) {var link = allLinks[i];var target = link.getAttribute('target');if (target && target == '_blank') {link.setAttribute('target','_self');} } }`

but in a website this script should be injected in the footer, not in head, so again not sure how this can be implemented. Or maybe I am missing something.

Idi

**Comment by christianswanepoel** [comment]
I circumvented this limitation, using a GET string to separate Jasonelle vs web browser traffic. I then inject the following javascript to remove all HTML target="_blank"

See below the Javascript  I used, both work.

**a) jQuery version** 
```
<script type='text/javascript'>
	$(document).ready(function(){
		$('a[target="_blank"]').removeAttr('target');
	}); 
</script>
```


**b) Javascript version**	
```
<script type='text/javascript'>
	function myFunction() {
  		var x = document.getElementsByTagName("A");
  		var i;
  		for (i = 0; i < x.length; i++) {
   		 x[i].removeAttribute("target");
  		}
	}
	window.onload=myFunction;
</script>
```

**Comment by idimeca** [comment]
You added this in the website I suppose. I am looking to do this from the app, via the json file or by editing core.

**Comment by idimeca** [comment]
How did you use the Get string, is there any if statement related to the app?

I am trying to use $agent.inject but with no result so far.

**Comment by christianswanepoel** [comment]
I am a Web Dev and its easier for me to farm off what I can to my Web Server.  Basically, I set a session var or cookie using a GET (on first load), and then have the web server do the redirect if the session is not set (Guess you could use jasonelle's POST syntax too). 

GET Sample:
```
"background": {
        "type": "html",
        "url": "http://myapp.com?app=true",
        "action": {
          "trigger": "handleLink"
        }
  }
```

The following link shows my example GET, and it includes a basic Jasonelle IF/ELSE statement.
https://www.jasonbase.com/things/87Md.json

**Comment by idimeca** [comment]
FYI, I ended up adding the js I posted above directly into 'agent.js' file and it works as it should. Finally :)

Idi

**Comment by christianswanepoel** [comment]
Thank you for the feedback. I will add that to mine then as well.

**Comment by clsource** [comment]
The user `eperonetti` in slack posted this. 
Maybe should be considered to add to the core.

```
For everyone who wants to remplace target _blank with _self =D. Just go make some modif in the source code of Jasonette.
`---------
/* IOS */
---------
-- Add the following code to the file JasonAgentService.m at the line 118

//Code added to replace all the target _blank with _self
//Adding externallink: at the start of the link to detect it in Jasonette code
//Handling external links in the Jasonette code.
NSString *script_replace = @"javascript: var allLinks = document.getElementsByTagName('a'); if (allLinks) {var i;for (i=0; i<allLinks.length; i++) {var link = allLinks[i];var target = link.getAttribute('target'); if (target && target == '_blank') {link.setAttribute('target','_self')}}}";
NSString *script_raw = [raw stringByAppendingString:script_replace];
[webView evaluateJavaScript:script_raw completionHandler:^(id _Nullable res, NSError * _Nullable error) {
    NSLog(@"Script to relpace all links with target _blank with _self.");
}];

-------------
/* Android */
-------------
-- Replace the following code on the java/com/nanoxi/ich/Service/agent/JasonAgentService.java file on between the lines 380 -> 384

if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.KITKAT) {
    view.evaluateJavascript(injection_script + " " + interface_script, null);
} else {
    view.loadUrl("javascript:" + injection_script + " " + interface_script);
}

-- With

//Added to replace the targets _blank with _self and to add externallink: at the start of the links
String script_replace = "var allLinks = document.getElementsByTagName('a'); if (allLinks) {var i;for (i=0; i<allLinks.length; i++) {var link = allLinks[i];var target = link.getAttribute('target'); if (target && target == '_blank') {link.setAttribute('target','_self')}}}";
if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.KITKAT) {
    view.evaluateJavascript(injection_script + " " + interface_script, null);
    view.evaluateJavascript(script_replace, null); //Added to replace _blank target with _self
} else {
    view.loadUrl("javascript:" + injection_script + " " + interface_script);
    view.loadUrl("javascript:" + script_replace); //Added to replace _blank target with _self
}`
```

**Comment by clsource** [comment]
> I am a Web Dev and its easier for me to farm off what I can to my Web Server. Basically, I set a session var or cookie using a GET (on first load), and then have the web server do the redirect if the session is not set (Guess you could use jasonelle's POST syntax too).
> 
> GET Sample:
> 
> ```
> "background": {
>         "type": "html",
>         "url": "http://myapp.com?app=true",
>         "action": {
>           "trigger": "handleLink"
>         }
>   }
> ```
> 
> The following link shows my example GET, and it includes a basic Jasonelle IF/ELSE statement.
> https://www.jasonbase.com/things/87Md.json

Please @christianswanepoel if you got a copy of that code. Please post it here since jasonbase is dead 😢 . Thanks.

**Comment by christianswanepoel** [comment]
The following code shows a basic IF/ELSE statement - it checks IF the URL "does not contain google" ELSE process normally.

```{
    "$jason": {
        "head": {
            "title": "External - Links",
            "description": "Opens tab if external link",
            "actions": {
                "handleLink": [
                    {
                        "{{#if $jason.url.indexOf('google') == -1 }}": {
                            "type": "$href",
                            "options": {
                                "url": "{{$jason.url}}",
                                "view": "web"
                            }
                        }
                    },
                    {
                       "{{#else}}": {
                           "type": "$default"
                       }
                    }
                ]
             }
        },
        "body": {
            "background": {
                "type": "html",
                "url": "https://www.google.com",
                "action": {
                    "trigger": "handleLink"
                }
            }
        }
    }
}
```

**Comment by clsource** [comment]
thanks 👍

**Comment by idimeca** [comment]
The problem with scripts is that they are loaded onPageFinished.

I am trying to add scripts onPageStarted but this does not seem to work in Jasonelle? Anyone found a way around?

**Comment by clsource** [comment]
The js files are loaded in the `JasonParser` file. So maybe an option to add libs could be possible

https://github.com/jasonelle/jasonette-ios/blob/master/app/Jasonette/JasonParser.m

**Comment by clsource** [comment]
https://github.com/jasonelle/jasonelle/wiki/Delete-iOS-target=_blank-Links
