### ISSUE TITLE
Flash on/off button whilst using $vision?

### ISSUE THREAD

**Issue by veglinus** [jasonelle-archive/jasonelle-v2#27]
Has anyone successfully implemented an on/off button for flash(torch) whilst using the $vision api? I've seen some threads on stackoverflow about doing it with the google vision api.
https://stackoverflow.com/questions/35811411/accessing-autofocus-flash-with-google-vision-barcode-reader - Not sure if this would interfere with the existing $vision Jasonette code or not though.

Just wondering if someone has already done this and if they're willing to share their code if that's the case. Any tips?

**Comment by clsource** [comment]
That could be done using an extension 👍 

https://github.com/jasonelle/docs/tree/develop/examples/jasonette/extensions/android/console-action
