### ISSUE TITLE
Push notification detection by app

### ISSUE THREAD

**Issue by christianswanepoel** [jasonelle-archive/jasonelle-v2#28]
I have Firebase Cloud Messaging working, on Android, the android message center functions as expected but clicking on the app does not...

e.g
I created a message in Firebase Cloud Messaging "notification admin", and added a "URL" with a link to a random Jasonette JSON file. 

The message delivers as expected, and clicking on the message in notification center, on the Android device, the defined Firebase URL opens in the app, notifies Firebase, and resets notification center and app badge. 

However, clicking on the Android app, with the notification badge active, will only open the app to the app's default view and not reset the app badge, nor notify Firebase Cloud Messaging of the access.

I am guessing I need to add some code to my JSON file, but what?

**Comment by clsource** [comment]
I believe this has to do with https://en.wikipedia.org/wiki/Mobile_deep_linking
If you could provide some example dev environment and code so I can test maybe it could be done 👍

**Comment by christianswanepoel** [comment]
I am using the default Firebase Cloud Messaging config method (https://firebase.google.com/docs/cloud-messaging/android/client), and latest Jasonelle-Android build. Then using "Additional options" in https://console.firebase.google.com, I add "Custom data" key: "url" and value: I point to any Jasonette JSON URL. 

As mentioned clicking on the message centre it deep links, clicking on the Jasonette/Jasonelle app icon it does not deep link.

**Comment by clsource** [comment]
this happends on iOS as well?

**Comment by christianswanepoel** [comment]
iOS does something completely different using the same JSON / Firebase:

1. iOS does not get an app badge
2. iOS does not deep link at all
