### ISSUE TITLE
TODO: Improve Code editor in Jasonbase

### ISSUE THREAD

**Issue by clsource** [jasonelle-archive/jasonelle-v2#30]
Jasonbase code editor is a simple `TextArea`. 
If it can be integrated with [https://ace.c9.io/](https://ace.c9.io/) and improve the syntax validation and highlighting before sending. It could improve the developer experience.

**Comment by clsource** [comment]
The html for the home page is here

https://github.com/jasonelle/jasonbase/blob/master/pw/site/templates/views/home.php

The html for the edit page is here

https://github.com/jasonelle/jasonbase/blob/master/pw/site/templates/views/edit.php

**Comment by clsource** [comment]
@juanbrujo wants to help out with this 👍

**Comment by lixas** [comment]
I have snippets plugin for ace type editor for Jasonette (for rapid development). Maybe it could be added to editor. It's here https://github.com/lixas/c9JasonetteSnippets

**Comment by clsource** [comment]
@lixas cool,  I don´t know if the ace editor support snippets but maybe it could be added. Thanks.

**Comment by juanbrujo** [comment]
@clsource added ACE with Eclipse theme, as you see in the preview:

![Screen Shot 2019-03-11 at 11 34 23](https://user-images.githubusercontent.com/362186/54132343-d66b1780-43f2-11e9-8131-edc9c8f47f61.png)

Steps:

1. Replace the `<textarea id="json"></textarea)` with:

```html
<div class="editor-wrapper">
   <div id="json" class="editor"></div>
</div>
```
2. Add this to CSS:

```css
.editor-wrapper {
    position: relative;
    min-height: 300px;
    border: 1px solid #ccc;
}
.editor {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
}
```

3. Add this scripts, external or internal:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.3/ace.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.3/mode-json.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.3/theme-eclipse.js"></script>
```

4. Initialize the script:

```javascript
var editor = ace.edit("json");
editor.setTheme("ace/theme/eclipse");
editor.session.setMode("ace/mode/json");
```

**Comment by clsource** [comment]
@juanbrujo thanks! 👍

**Comment by clsource** [comment]
@lixas I noticed your code has not a proper License. Please choose a License otherwise I could not use your code 👍  thanks.

**Comment by lixas** [comment]
@clsource added MIT license. You are free to use
