### ISSUE TITLE
Background URL App Rotate

### ISSUE THREAD

**Issue by francoisramos** [jasonelle-archive/jasonelle-v2#35]
The App using a web page as background, something like:

`"templates": {
				"body": {
					"background": {
						"type": "html",
						"url": "https://www.example.com/app",
						"action": {
							"trigger": "visit"
						}
					}
				}
			}`

The issue is, every time the device (any device - iOS or Android) is rotated, the background web page refreshes.

Is there a way to prevent this from happening?

**Comment by christianswanepoel** [comment]
I can only reproduce the issue on my Android apps and not iOS. @mappemaq can you confirm it happens in both iOS and Android? 
@clsource could this not be the code that fixed iOS version? https://github.com/jasonelle/jasonelle/issues/29

**Comment by francoisramos** [comment]
you are right @christianswanepoel, only Android apps has this issue.

**Comment by clsource** [comment]
After working on the iOS in the develop branch now the background view correctly works. 
Android part should be revised by @panterozo

**Comment by panterozo** [comment]
I was working on a possible fix for it. You are welcome to discuss the implementation [here](https://github.com/jasonelle/jasonette-android/pull/4). I still have my doubts about the way I get to it. It would be nice to have some test on it.
