### ISSUE TITLE
Using jasonette for a section of the screen

### ISSUE THREAD

**Issue by rakesh-pachawa** [jasonelle-archive/jasonelle-v2#36]
hi.

All jasonette docs and sample apps are using full screen for jasonette driven ui.

How to use jasonette for only a section of the screen?

Thanks

**Comment by christianswanepoel** [comment]
I am assuming you asking for multi apps on one screen e.g. split screen.
Jasonette is not able to do this currently, but feel free to add this via the native code and share ;)

**Comment by clsource** [comment]
In iOS you can instantiate a `JasonViewController` in your own code. So you can for example have half jasonette half native view controller.
