### ISSUE TITLE
how to pass query params to post request?

### ISSUE THREAD

**Issue by Pvybhav** [jasonelle-archive/jasonelle-v2#39]
```
"type": "$network.request",
    "options": {
      "url": "https://www.jasonclient.org/users/sign_in.json",
      "method": "post",
      "data": {
        "username": "{{$jason.username}}",
        "password": "{{$jason.password}}"
      }
    }
```

**Comment by lixas** [comment]
Its correct way. 
Because you do not post full forking code (just very minimal part of your code) noone will be able to fully solve your issue. Probably, it is `$jason.username` and `$jason.password` variables are empty in you case.
What kind of request do you get from server side (when looking in access logs)?

**Comment by Pvybhav** [comment]
How can i access the data from nodejs post route?

**Comment by lixas** [comment]
Then log those requests into file from your nodejs code- it will be easier to debug

**Comment by Pvybhav** [comment]
If I use 'GET' request, then it is sending data(username and password) in query parameters. If I use 'POST' type then it is not sending any values in request for ex. (req.body, req.params, req.query)

**Comment by clsource** [comment]
I believe this has to do more with the server implementation than the post request.

Try setting headers to  `application/json` or `application/x-www-form-urlencoded`

**Comment by Pvybhav** [comment]
` "action": {
                        "type": "$network.request",
                        "options": {
                          "url": "http://PORT:5000/sendJsonOutput",
                          "method": "post",
                          "data": {
                            "user_id": "1234",
                            "message": "Hello there"
                          },
                          "header": {
                            "content_type": "json"
                          }
                        },
                        "success": {
                          "type": "$util.toast",
                          "options": {
                            "text": "NETWORK REQUEST SUCCESS",
                            "type": "warning"
                          }
                        },
                        "error": {
                          "type": "$util.toast",
                          "options": {
                            "text": "NETWORK REQUEST ERROR",
                            "type": "warning"
                          }
                        }
                      }`
The above code worked for me and able to access the **_data_** object in server using **_req.body_**

@clsource @lixas **Thanks**
