### ISSUE TITLE
Pre-built updated 'jason' app?

### ISSUE THREAD

**Issue by schweini** [jasonelle-archive/jasonelle-v2#42]
I understand that the previous version of the Jason demo app has stopped working.

While I'm waiting for Android Studio to download and install, in order to build a jasonelle version of the demo app, may I ask why there is no no pre-built .apk of the Jason app available on github, or even the Play Store?

I would have really liked to test-drive the whole Jasonelle concept before having to build the whole thing in Android Studio...

**Comment by clsource** [comment]
It can be done by distributing an APK. I have to discover how to do that though and upload to the releases version.

**Comment by clsource** [comment]
Ok here you go 

https://github.com/jasonelle/jasonelle/releases/download/v1.0/jasonapp.apk

Thanks to @TakaKeiji for the help

**Comment by schweini** [comment]
Awesome! Thanks!
