### ISSUE TITLE
DeepLinking Examples

### ISSUE THREAD

**Issue by clsource** [jasonelle-archive/jasonelle-v2#45]
Create deeplinking examples both in android and iOS. Add them to the docs.

**Comment by clsource** [comment]
https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html

**Comment by clsource** [comment]
https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app

**Comment by Tobi-La** [comment]
Is there a doc for this now? Issue is closed, but I can't find anything.

**Comment by clsource** [comment]
It was closed because low bandwith to deal with it 👍  but maybe it can be done.
Deep linking is not difficult to do and for the message it should follow the same json syntax of the app.
