### ISSUE TITLE
OneSignal Android 

### ISSUE THREAD

**Issue by christianswanepoel** [jasonelle-archive/jasonelle-v2#46]
I am trying to integrate OneSignal messaging into my App, but their integration documentation specifications clash with existing code in Jasonette Android - (as a followup a conversation with @panterozo) 

See their integration documentation for further details:
https://documentation.onesignal.com/docs/android-sdk-setup#section-2-add-required-code

PS As an extension to this, It would be great to have a way to switch-on / activate a push service like OneSignal easier. e.g. build up libraries one could activate or deactivate as needed.

**Comment by aditi-sof** [comment]
Hello @christianswanepoel - Were you able to figure out a solution?

**Comment by christianswanepoel** [comment]
Hi @aditi-sof - no I have not got OneSignal to work on Android. I am still using Firebase for my messages.

**Comment by clsource** [comment]
Thanks @christianswanepoel  👍 

I added some docs to clarify a little about notifications https://github.com/jasonelle/docs/wiki/Push-Notifications 
The extensions should be created for each service provider.

The idea to have on/off solution integrated with the framework to enable or disable such services is doable, but I believe it would add too much bloat.

The best way it should be is creating an example implementation and documenting. So the community can make their own push notification service extensions.

Here is a sample extension implementation to Firebase :)

https://github.com/jasonelle/docs/tree/develop/examples/jasonette/extensions/ios/FirebaseFCMToken

For now i´m closing this 💯
