### ISSUE TITLE
Jasonelle for Dummies

### ISSUE THREAD

**Issue by Mashiane** [jasonelle-archive/jasonelle-v2#47]
Hi

I'd like to test this out but I think I am overwhelmed. This is the approach im thinking.

1. Have this running on my laptop. How do I set it up using Laragon for example?
2. Create a 'Hello' world example to get me started.
3. How do I get the example working on my phone?

Is there a step by step tutorial on how to use this please?

Thanks

**Comment by christianswanepoel** [comment]
Hi
Quickstart: https://jasonelle.com/jasonette-old-docs/#quickstart
Official documentation: https://jasonelle.com/docs/
Do a tutorial: https://jasonelle.com/docs/jasonette-tutorials.html#turn-your-website-into-a-mobile-app-with-7-lines-of-json

**Comment by clsource** [comment]
Thanks for answering @christianswanepoel  :)
