### ISSUE TITLE
settings.plist 

### ISSUE THREAD

**Issue by BillMeyerRSA** [jasonelle-archive/jasonelle-v2#50]
Very simple issue
Compiled and build with AndroidStudio
Run in Virtual Android device
Message says make changes to "settings.plist"

Cannot find any settings.plist, but that seems to be an iPhone file.
What is the equivalent for it in the Android App?

**Comment by clsource** [comment]
Normally the file refered is `strings.xml` 
https://github.com/jasonelle/jasonette-android/blob/master/app/src/main/res/values/strings.xml

please provide an screenshot or steps to reproduce the issue in order to fix the message.

thanks :)

**Comment by BillMeyerRSA** [comment]
Got it thanks
Strange - did attach the screenshot first time, but somehow it got lost when posting. Here it is.
As I said - it was the first startup after building app. 

Another question - where would I find cell.js?
The original site is down with error, cannot find a copy of cell.js anywhere. 
Want to test the (archived) jasonette-web and see it will miss that dependency.
Thanks!
![JasonetteAndroid](https://user-images.githubusercontent.com/38781014/64276069-4f34d180-cf47-11e9-845a-e420b16f4b5e.png)
- thanks

**Comment by clsource** [comment]
ah ok that seems something inside hello.json nothing complicated to fix.

here is the latest cell.js code https://github.com/jasonelle/cell.js
