### ISSUE TITLE
Problems getting jasonette-web running

### ISSUE THREAD

**Issue by BillMeyerRSA** [jasonelle-archive/jasonelle-v2#51]
Hi
I am trying to get jasonette-web up and running. It looks like a really good way to prototype an app. Also having a web based platform for apps is also something that I would want to do, not just Android / iOS app. 

Running into some issues as much of the links at [https://tojson.co/node_module] seem to be dead at the moment. 
I am downloading the files and linking them in the /dist folder, e.g. the cell.js.
So far missing these:
- lint.js 
- javascript-lint.js
- json-lint.js 
- closebrackets.js 
- matchbrackets.js

**Problem Description**
Get these error messages in console
index.min.js:1 Invalid asm.js: Unexpected token
index.html:18 GET https://tojson.co/node_modules/jsonlint/lib/jsonlint.js net::ERR_CONNECTION_REFUSED
index.html:19 GET https://tojson.co/node_modules/codemirror/addon/lint/lint.js net::ERR_CONNECTION_REFUSED
index.html:20 GET https://tojson.co/node_modules/codemirror/addon/lint/javascript-lint.js net::ERR_CONNECTION_REFUSED
index.html:21 GET https://tojson.co/node_modules/codemirror/addon/lint/json-lint.js net::ERR_CONNECTION_REFUSED
index.html:22 GET https://tojson.co/node_modules/codemirror/addon/edit/closebrackets.js net::ERR_CONNECTION_REFUSED
cell.js:356 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
(anonymous) @ cell.js:356
detect @ cell.js:354
create @ cell.js:379
(anonymous) @ cell.js:404
load (async)
(anonymous) @ cell.js:403
(anonymous) @ cell.js:408
cell.js:286 Uncaught TypeError: Cannot read property 'set' of undefined
    at HTMLDivElement.set (cell.js:286)
    at Object.update (cell.js:156)
    at Object.build (cell.js:123)
    at DocumentFragment.$context.DocumentFragment.$build.$context.Element.$build (cell.js:370)
    at cell.js:211
    at Array.forEach (<anonymous>)
    at Object.$components (cell.js:210)
    at Object.update (cell.js:147)
    at Object.build (cell.js:123)
    at HTMLBodyElement.$context.DocumentFragment.$build.$context.Element.$build (cell.js:370)
set @ cell.js:286
update @ cell.js:156
build @ cell.js:123
$context.DocumentFragment.$build.$context.Element.$build @ cell.js:370
(anonymous) @ cell.js:211
$components @ cell.js:210
update @ cell.js:147
build @ cell.js:123
$context.DocumentFragment.$build.$context.Element.$build @ cell.js:370
(anonymous) @ cell.js:380
create @ cell.js:379
(anonymous) @ cell.js:404
load (async)
(anonymous) @ cell.js:403
(anonymous) @ cell.js:408
index.html:23 GET https://tojson.co/node_modules/codemirror/addon/edit/matchbrackets.js net::ERR_CONNECTION_REFUSED
**Screenshots**

![jasonette-web-01](https://user-images.githubusercontent.com/38781014/64342984-f2d7bd80-cfeb-11e9-8339-aa890b505647.png)

**Futher Context**
After including cell.js in /dist getting new error in console:

cell.js:356 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
(anonymous) @ cell.js:356
detect @ cell.js:354
create @ cell.js:379
(anonymous) @ cell.js:404
load (async)
(anonymous) @ cell.js:403
(anonymous) @ cell.js:408
cell.js:286 Uncaught TypeError: Cannot read property 'set' of undefined
    at HTMLDivElement.set (cell.js:286)
    at Object.update (cell.js:156)
    at Object.build (cell.js:123)
    at DocumentFragment.$context.DocumentFragment.$build.$context.Element.$build (cell.js:370)
    at cell.js:211
    at Array.forEach (<anonymous>)
    at Object.$components (cell.js:210)
    at Object.update (cell.js:147)
    at Object.build (cell.js:123)
    at HTMLBodyElement.$context.DocumentFragment.$build.$context.Element.$build (cell.js:370)
set @ cell.js:286
update @ cell.js:156
build @ cell.js:123
$context.DocumentFragment.$build.$context.Element.$build @ cell.js:370
(anonymous) @ cell.js:211
$components @ cell.js:210
update @ cell.js:147
build @ cell.js:123
$context.DocumentFragment.$build.$context.Element.$build @ cell.js:370
(anonymous) @ cell.js:380
create @ cell.js:379
(anonymous) @ cell.js:404
load (async)
(anonymous) @ cell.js:403
(anonymous) @ cell.js:408

**Comment by clsource** [comment]
web.jasonette.com is an unmaintained project.
If you could revive it and rejuvenate it to its former glory that would be awesome

here is a working copy

http://web.archive.org/web/20180208024512/http://web.jasonette.com/items/171/edit

Although a simple web version a handy I think its better to stick with a simulator that uses the same native components. Maybe a project could be worked on that updates on change to supply the need for this project.

**Comment by BillMeyerRSA** [comment]
Thanks. (This post just for info in case someone else get to this point, found the missing files here here)
- https://codemirror.net/addon/lint/
- https://github.com/zaach/jsonlint
- https://chromedevtools.github.io/source-docs/source/front_end/cm/closebrackets.js.src.html

Downloaded into /dist directory and updated the links. 

That left me with this error:
Invalid asm.js: Unexpected token
cell.js:356 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
(anonymous) @ cell.js:356
detect @ cell.js:354
create @ cell.js:379
(anonymous) @ cell.js:404
load (async)
(anonymous) @ cell.js:403
(anonymous) @ cell.js:408
cell.js:286 Uncaught TypeError: Cannot read property 'set' of undefined
    at HTMLDivElement.set (cell.js:286)
    at Object.update (cell.js:156)
    at Object.build (cell.js:123)
    at DocumentFragment.$context.DocumentFragment.$build.$context.Element.$build (cell.js:370)
    at cell.js:211
    at Array.forEach (<anonymous>)
    at Object.$components (cell.js:210)
    at Object.update (cell.js:147)
    at Object.build (cell.js:123)
    at HTMLBodyElement.$context.DocumentFragment.$build.$context.Element.$build (cell.js:370)
set @ cell.js:286
update @ cell.js:156
build @ cell.js:123
$context.DocumentFragment.$build.$context.Element.$build @ cell.js:370
(anonymous) @ cell.js:211
$components @ cell.js:210
update @ cell.js:147
build @ cell.js:123
$context.DocumentFragment.$build.$context.Element.$build @ cell.js:370
(anonymous) @ cell.js:380
create @ cell.js:379
(anonymous) @ cell.js:404
load (async)
(anonymous) @ cell.js:403
(anonymous) @ cell.js:408

![jasonette-web-02](https://user-images.githubusercontent.com/38781014/64411614-e1df8880-d08d-11e9-99f3-25af9c82e7c5.png)

**Comment by BillMeyerRSA** [comment]
Another comment for those who want to give it a shot. 
I replaced the link to cell.js in index.html to point to
  https://rawgit.com/intercellular/cell/inherit/cell.js
Reloaded page... Seems like some life is coming back!!!

![jasonette-web-03 png](https://user-images.githubusercontent.com/38781014/64416989-84046e00-d098-11e9-9b54-c895357f44e8.png)

Bad news for this solution is on rawgit page:
![rawgit-message](https://user-images.githubusercontent.com/38781014/64417088-b9a95700-d098-11e9-959c-55704921a05f.png)

This would mean the https://selecttransform.github.io/playground/ is going to go down around October 2019.

![selecttransform](https://user-images.githubusercontent.com/38781014/64417524-8915ed00-d099-11e9-97cc-272d9844ceac.png)

**Comment by clsource** [comment]
The playground is sound and safe here

http://jasonelle.com/docs/ja-js-selector-transformer.html

https://jasonelle.com/docs/playground-ja/

https://github.com/jasonelle/docs/tree/develop/playground-ja

**Comment by clsource** [comment]
Maybe the web editor part can be added to base.jasonelle.com so the editor is better. I will evaluate that
