### ISSUE TITLE
ITMS-90683: Missing Purpose String in Info.plist 

### ISSUE THREAD

**Issue by mrshawnj** [jasonelle-archive/jasonelle-v2#52]
I get this email/error with a test upload to app store (trying to use $geo.get):

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

Best regards,

The App Store Team

**Comment by clsource** [comment]
Ok well it seems a new Apple requirement. should be fixed in the dev branch in a few days. Thanks for the report.
