### ISSUE TITLE
React and Smart TV apps

### ISSUE THREAD

**Issue by karneaud** [jasonelle-archive/jasonelle-v2#53]
hey guys,

just found this framework and sounds too good to be true. I have two questions...

1. Can i turn my react/ vuejs app into a jasonelle app? 
2. Does the jasonelle app work for android/ apple TV apps?

**Comment by clsource** [comment]
Hello, 

1 - YES using the $agents api 

https://jasonelle.com/jasonette-old-docs/agents/

2 - Maybe but should be tested.
