### ISSUE TITLE
Absolute positioning in json styling

### ISSUE THREAD

**Issue by GAGANsinghmsitece** [jasonelle-archive/jasonelle-v2#57]
**Is your feature request related to a problem? Please describe.**
I'm trying to make a footer with links in which 1st tab does not has same address as that of first view. Morever,it's not on the root view.

**Describe the solution you'd like**
There should be absolute positioning like that in css. Then,we can just assign absolute positioning to items which would make this product robust

**Describe alternatives you've considered**
I use layers for absolute positoning but since i need to assign position to group of links rather than single item. Hence, it's not working

**Identify which component would benefit from this feature**

- [ ] Jasonette iOS
- [ ] Jasonette Android

**Comment by clsource** [comment]
Hello, thanks for the request.

I understand that this can be achieved by using percentages. For example if you want to lock the item to the footer you could use `"top": "100%-50"`. this means it will go to the bottom and then decrease 50 pixels.

If you want to apply the values to a group of items you could also use variables like this `"top":"100%-{{$get.mycustomheight}}"`

with those settings. It is possible to achieve the desing you need?.

Thanks :)

**Comment by GAGANsinghmsitece** [comment]
Thanks for your response. Please your docs about setting position as "100%-50". I guess i need to use layer for it. Am i right?

**Comment by GAGANsinghmsitece** [comment]
![Screenshot_20191001-091555](https://user-images.githubusercontent.com/37043052/65932753-928e3d00-e42c-11e9-9066-0be041138789.png)
I tried to nest items into layers but it is not working as currently layer only support image or label. Can you please show any code snippet regarding this

**Comment by clsource** [comment]
This is some example of using layers inside jasonpedia.

The documentation about pixels and percentages are here

https://jasonelle.com/jasonette-old-docs/convention/#3-pixels-and-percentage

This is an example of layers

https://github.com/jasonelle/docs/blob/develop/examples/jasonette/apps/jasonpedia/view/layer/dynamic.json

https://jasonelle.com/jasonette-old-docs/document/#bodylayers

:)
