### ISSUE TITLE
Web container not supporting upload feature

### ISSUE THREAD

**Issue by GAGANsinghmsitece** [jasonelle-archive/jasonelle-v2#58]
I'm trying to show a website in web container which has a upload button. But when user clicks on it, it does not open image picker. Any idea how can i achieve same?

**Comment by clsource** [comment]
Hello, 
Some features are blocked inside webcontainers by Apple / Google. So to achieve that you would need a native wrapper.

In jasonelle you could use https://jasonelle.com/jasonette-old-docs/actions/#mediapicker

And call it from. the webview using Agent

https://jasonelle.com/jasonette-old-docs/agents/

https://jasonelle.com/docs/how-to-guides.html#how-to-overwrite-links-in-a-webview

Also be sure that you add `"type":"$default"` to the webview background to trigger normal flow of actions https://jasonelle.com/docs/jasonette-tutorials.html#turn-your-website-into-a-mobile-app-with-7-lines-of-json

**Comment by GAGANsinghmsitece** [comment]
Hello, i refer to the links that you provide. What i understood that we can can call agents from web page to jasonette and vice-versa. But how that event will can media picker widget. I even explore github repositories related to agents. Can you please provide a example where a web page is calling a action

**Comment by clsource** [comment]
Here 

https://github.com/jasonelle/beerjs
https://github.com/jasonelle/docs/tree/develop/examples/jasonette/apps/jasonpedia/webcontainer/agent

Is not difficult, just use the `$agent` variable and you can communicate between web and native.
