### ISSUE TITLE
how to make network request and display response on screen?

### ISSUE THREAD

**Issue by Pvybhav** [jasonelle-archive/jasonelle-v2#59]
how to make network request and display response on screen?

**Comment by clsource** [comment]
There a lot of ways.

You can use the `$network`action, the `$require`or using `mixins` to fetch the data. save it inside a variable and use that variable to create some views.

https://github.com/jasonelle/docs/tree/develop/examples/jasonette/apps/jasonpedia/action/network

https://jasonelle.com/jasonette-old-docs/mixin/#mix-remote-and-local-mixins
https://jasonelle.com/jasonette-old-docs/actions/#require_1
https://jasonelle.com/jasonette-old-docs/actions/#network-request-and-then-render
