### ISSUE TITLE
cannot compile develop branch due to error in overriding onBackPress()

### ISSUE THREAD

**Issue by cpg** [jasonelle-archive/jasonelle-v2#61]
**Describe the bug**
Error compiling the `develop` branch. ToT as of Oct 5 2019.

Had to change `protected` to `public` in `onBackPress()` to get it to compile successfully

**To Reproduce**
1. Clone android project
2. switch to `develop` branch
3. compile
4. Experience error

**Expected behavior**
Compilation finishes with no errors

**Screenshots**
https://www.dropbox.com/s/ryb8sgfb5pl83ev/Screen%20Shot%202019-10-04%20at%209.09.16%20PM.png?dl=0

**Additional context**
Mac OS X platform

**Comment by panterozo** [comment]
Hi @cpg.. I change this method to public as you suggested in [commit](https://github.com/jasonelle/jasonette-android/commit/6956f80fd55825298b251ea5596cfc891e21fc80). It was also added into master branch.
