### ISSUE TITLE
how to set outline of items to none?

### ISSUE THREAD

**Issue by GAGANsinghmsitece** [jasonelle-archive/jasonelle-v2#63]
**Problem Description**
I'm trying to build  a jasonelle app in android. When i use items, it comes with a default border at bottom which is #ffffff in colour.  I don't need it in my app so i attach a class  and set border_width to 0 but it's not working 
**Screenshots**
![Screenshot_20191018-075017](https://user-images.githubusercontent.com/37043052/67061210-3aba3a80-f17d-11e9-980b-1fa41d874001.png)

**Sample Code**

```

      "sections": [{
        "items": [
          

          {
            "type": "vertical",
            "style":{
              "spacing":"10"
            },
            "components": [
          {% for c in choice %}{
              "type": "label",
              "class":"options",
              "text": "{{c}}",
              "href":{
                "url":"{{var}}://{{site}}/json/{{c}}/register",
                "loading":"true"
              }
            },
{% endfor %}
          ]
          }
        ]
      }]
```

**Futher Context**

**Comment by clsource** [comment]
hello that border can be used as 

```
"body": {
                    "style": {
                        "border": "none"
                    }
}
```
