### ISSUE TITLE
Easiest way to use javascript in an action

### ISSUE THREAD

**Issue by rolloclarke** [jasonelle-archive/jasonelle-v2#66]
Hi! I've raised some GitHub issues about $agent bugs in android (#64, #65). I'm very new to this, but it makes me think people aren't using the agent functionality much. Perhaps I've missed something. A user enters some text, then taps save. What's the easiest way to manipulate that user input with javascript before storing it say with a $global.set action?

I know I can use inline javascript but that seems clunky.

**Comment by clsource** [comment]
Hello, the best way is to include js using https://jasonelle.com/jasonette-old-docs/actions/#scriptinclude and then call the function using `{{myfunction($jason)}}` to manipulate the user input :)

**Comment by rolloclarke** [comment]
Thanks! (I was missing something). I will try things this way too
