### ISSUE TITLE
$agent.request uses different Browser agent string than $href(actual mobile browser)

### ISSUE THREAD

**Issue by yogistraAnderson** [jasonelle-archive/jasonelle-v2#67]
I have discovered the situation in the title while trying to get my authentication scheme going on the JSONETTE platform. 

My solution involves using $agent.request which calls a javascript function performing ajax requests, submitting a userid/password pair to get an authentication token. 

Then further requests will use that token in the requests to the web server.

However part of my app calls for opening a web browser window to the same server I have been authenticated against, and supplying the token in the URL.

It has been failing to go thru for over a day now, when I have finally tracked down the problem that the authentication lib remembers the agent that requested the initial token and will not respond to a different agent.

I have discovered that JASONETTE $agent.request uses a different browser agent string than the default web browser. 

These are the strings I have observed in my situation:

 browser.request
 "Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-A205G) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/10.1 Chrome/71.0.3578.99 Mobile Safari/537.36"
 
 
agent.request
 "Mozilla/5.0 (Linux; Android 9; SM-A205G Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.116 Mobile Safari/537.36"
 
I realize that maybe JSONETTE does not have control over the default browser.... but there should be some way that we can get this done consistently, after all the $href and $agent feature is offered by the API, and they should work hand in hand. 

I will have to solve this by hard coding the browser agent in the $agent request to match the browser...

It would be great if there is someway to set the $href request headers (ala, $network) so we can sync the headers. If there is a consistent way to query/set the agents of these two sections of the API that would be very helpful.

Also I have noticed $network.request also has a different browser agent: ""

**Comment by clsource** [comment]
Hello thanks for your issue. As today there is no way to change the browser agent string by api. But you can use headers 

https://stackoverflow.com/questions/42815087/sending-a-custom-user-agent-string-along-with-my-headers-fetch

example

```

  "type": "$network.request",
  "options": {
    "url": "example.com",
    "method": "post",
    "data": {
      "user_id": "fI9",
      "message": "Hello there"
    },
    "header": {
      "User-Agent": "Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-A205G) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/10.1 Chrome/71.0.3578.99 Mobile Safari/537.36"
    }
  },
  "success": {
    "type": "$render"
  },
  "error": {
    "type": "$util.alert",
    "options": {
      "title": "Error",
      "description": "Uh oh, something went wrong"
    }
  }
}
```

**Comment by yogistraAnderson** [comment]
Thanks for your response, I know I am being a pain in the rear. I am aware of the ability to change the agent in the $network.request. 

However I was trying to encapsulate a lot of my code that does several AJAX request to the server in a script I am calling via the $agent.request API. 

Not a deal breaker, I will be able to get my stuff done by utilizing $network.request, however maybe consider making the $agent.request agent used for making AJAX calls configurable.

**Comment by clsource** [comment]
hello @yogistraAnderson I´m not quite sure what are you trying to accomplish.

the `$agent.request` is normally used for calling javascript functions.

https://jasonelle.com/jasonette-old-docs/agents/

if you are trying to pass the user agent as a param you just need to send it to a function tha uses the param.

example

in javascript 
```js
const fetchWithUserAgent = uagent => {
const headers = new Headers({
    "Accept"       : "application/json",
    "Content-Type" : "application/json",
    "User-Agent"   : uagent
});

return fetch(url, {
    method  : 'GET', 
    headers : headers 
    // ... etc
}).then(response => response.json()).then(json => $agent.response(json));
}
```

in json

```json
{
  "type": "$agent.request",
  "options": {
    "method": "fetchWithUserAgent",
    "params": ["Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-A205G) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/10.1 Chrome/71.0.3578.99 Mobile Safari/537.36"]
  }
}
```

cheers 👍

**Comment by yogistraAnderson** [comment]
@clsource let me explain what I am doing so you can have a better idea


My app requires a sign in, which will give me a session token that I will use for subsequent requests, etc.

This is how I am going about it:

I am capturing a userid/password from the screen and passing that into an $agent.request,

thats linked to a javascript function. Now like you said, $agent.request was intended to call javascript functions, however I am also making AJAX requests to a server within that javascript function.

The userid/password is hashed and sent to the server which creates a session and returns that session id. At the point of this request, the agent string is captured by the server, it will use this to validate further requests using that session id. If they do not match, the requests will be rejected.

$agent.request, I suppose uses an internal browser whose agent string is captured when the AJAX calls are made in the function.

now when the session id is returned, I want to be able to use it for further $network.request or $href links, however all of these methods supply a different agent string to the server causing authentication problems

Here is my code:

agent calling code: 

```
{"type": "$agent.request",
							"options": {
							  "id": "crypto",
							  "method": "log_in",
							  "params":["{{$get.userid}}","{{$get.password}}","3","128"]              
							}}
```


agent code:

```
function log_in(userid,passwd,app_id,role_id){
			
	$.get("/ss/get_login_challenge.php",null,function(res){
			
		let challenge = res.data.challenge;
		let passhash = hashfunct(userid,"salt",passwd);
		let signed_chlg = signfunct(challenge,passhash);
			
			//try to log in
			$.get( ("/ss/do_login.php?user_id=" + userid.toLowerCase() + "&passhash=" + signed_chlg),null,function(res_login){
				if(res_login && res_login.err_code == 0){					
					$agent.response(data);
				}
			},"json");			
		}
	},"json");
}
```

Like I said, I have a solution to go around the limitations, however I am just posting, maybe my use case can be helpful in future development

**Comment by clsource** [comment]
It seems that you are using Jquery https://api.jquery.com/jQuery.get/
you could pass the headers in the request using something similar to this

```js
function log_in(userid,passwd,app_id,role_id){

    const userAgent = 'Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-A205G) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/10.1 Chrome/71.0.3578.99 Mobile Safari/537.36';

    $.get({
            url: "/ss/get_login_challenge.php",
            dataType: 'json',
            beforeSend: function(request) {
                request.setRequestHeader("User-Agent", userAgent);
            },
            success: function(res) {
                const challenge = res.data.challenge;
                const passhash = hashfunct(userid,"salt",passwd);
                const signed_chlg = signfunct(challenge,passhash);
                $.get({
                    url: "/ss/do_login.php?user_id=" + userid.toLowerCase() + "&passhash=" + signed_chlg,
                    beforeSend: function(request) {
                        request.setRequestHeader("User-Agent", userAgent);
                    },
                    dataType: 'json',
                    success:function(res_login) {
                        if(res_login && res_login.err_code == 0){
                            $agent.response();
                        }
                    }
                });
            }
    });
}
```

👍

**Comment by yogistraAnderson** [comment]
Thanks for your efforts. That solution is not really "stable". I saw it on stackoverflow previously.

I have modified the JSONETTE android app to check for a user-agent option for $agent.request and set if present.

Take care
