### ISSUE TITLE
$scroll bug?

### ISSUE THREAD

**Issue by mrshawnj** [jasonelle-archive/jasonelle-v2#68]
I'm trying to use $scroll bottom. I have on view and then I use "push" to transition to next view. I call "$scroll" with "bottom" option, and nothing happens in the current view. However, I notice when I click the back button to previous view, the previous view has now scrolled to the bottom.

**Comment by clsource** [comment]
Hello in which platform does this happens? have you got  a sample json? thanks.

**Comment by mrshawnj** [comment]
iOS... I can make some sample json, but don't have it at the moment

**Comment by mrshawnj** [comment]
I basically just tried after an action:

                                            "success":
                                            {
                                                    "type": "$scroll",
                                                    "options": {
                                                        "position": "bottom"
                                                    }
                                            }

**Comment by mrshawnj** [comment]
I also tried to substitute "top" instead of "bottom" to see what happens and this causes a crash:

 *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:usingPresentationValues:]: row (0) beyond bounds (0) for section (0).'

libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by clsource** [comment]
thanks for the report. I will check that action futher! 👍

**Comment by clsource** [comment]
Ok this will be checked in the next release. Thanks for your contribution 👍
