### ISSUE TITLE
$util.datepicker seems to crash

### ISSUE THREAD

**Issue by kcorey** [jasonelle-archive/jasonelle-v2#70]
**Describe the bug**
I started with the default demo.  Clicked the first link. Clicked on 'Action'.  clicked on $util.datepicker.

*crash*

**Example Jasonette Document URL**
The default jasonette script that comes with jasonette (It's ALIVE)

**To Reproduce**
1. Load default demo
2. Click on first link 'Check out Live DEMO'
3. Clicked on 'Action'
4. Clicked on $util.datepicker

*crash*

**Expected behavior**
To see a demo of the datepicker.

**Smartphone (please complete the following information):**
 - Device: Samsung S8+, Google Pixel 4XL
 - OS: Android 9.0 Pie, Android 10.0

**Compilation**:
 - Tested on Jason App?: Yes
 - Version 0.1.0, compiled locally from deb

**Comment by kcorey** [comment]
I've made a PR to fix this bug using standard dialogs:

https://github.com/jasonelle/jasonette-android/pull/9

**Comment by panterozo** [comment]
It was added the functional code [link](https://github.com/jasonelle/jasonette-android/commit/1a0d7171e4a305522f875983c552ac178f0d20e6)
