### ISSUE TITLE
How about a shake menu for developing?

### ISSUE THREAD

**Issue by kcorey** [jasonelle-archive/jasonelle-v2#71]
**Is your feature request related to a problem? Please describe.**

On the app I work on during the day we have a shake menu for development.  On our app we can shake the phone, and a screen shows up allowing us to change endpoints, configuration settings, restart the app (after the proper debuggers are attached), etc.

**Describe the solution you'd like**

I want to implement such a thing for Jasonelle.  In fact, if we have a shake detector in the app for development purposes, I'd like to make sure that it could be used as an Action by end users as well.

**Describe alternatives you've considered**

So, What I'm thinking: is that the shake action, by default, is configured to open file://shake.json.  That should have several settings like 'Current script', 'log net calls', 'toggle verbose logging', 'show logcat errors in a scrolling native dialog', or whatever.

In the strings.xml file, the string "file://shake.json" should be able to be modified by the end users in case they want to add it as an action in their own scripts.  They'd obviously lose all the dynamic environment setting, but Hey ho.

**Identify which component would benefit from this feature**

- [ ] Jasonette iOS
- [X] Jasonette Android
- [ ] Cell.js
- [ ] St.js
- [ ] Other

**Additional context**

Thoughts?

**Comment by clsource** [comment]
thanks!. Sounds like something that could be added. But since the new version will start to be created soon, I think this idea should be shelved and revised later when all the core parts are done. I recommend adding this as an extension though to the current version and not in the core so anyone could optionally start using this. :)
