### ISSUE TITLE
What about Shortcuts on Home Screen (both iOS and Android)?

### ISSUE THREAD

**Issue by kcorey** [jasonelle-archive/jasonelle-v2#73]
**Is your feature request related to a problem? Please describe.**
Assuming we have some sort of control screen (as in my shake proposal), we could provide a button or menu item for users to have an 'Add To Home Screen' functionality. (This add to home screen thing might even be exposed for Jasonelle developers to use.)

This would mean that with one app in the Stores, a user would be able to support multiple Jasonelle apps on one phone...and that the scripts could be edited on the phone itself.

**Describe the solution you'd like**
The way I imagine it working:  
1) Shake the phone to bring up Control Menu
2) One of the items there is "Load new script", and another is "Save This Script to Home Screen"
3) The user can click on "Load new script" to be taken to a script chooser in local storage (on Android, maybe even the SDCard).
4) The user selects a given script, and it runs.
5) The user shakes again, then clicks "Add to Home Screen".
6) Some time later, the user clicks on the shortcut.  Jasonelle is loaded, and the chosen script is launched directly.

On Android, this link described how it could be done: (https://stackoverflow.com/questions/16873256/how-to-add-shortcut-to-home-screen-in-android-programmatically)
On iOS it might be something like this: (https://swiftrocks.com/adding-deeplink-shortcuts-to-the-ios-home-screen.html)

**Describe alternatives you've considered**
Another (possibly complementary) solution would be to support deep linking from web sites with a custom url scheme (https://medium.com/@ageitgey/everything-you-need-to-know-about-implementing-ios-and-android-mobile-deep-linking-f4348b265b49)

**Identify which component would benefit from this feature**

- [X] Jasonette iOS
- [X] Jasonette Android
- [ ] Cell.js
- [ ] St.js
- [ ] Other

**Additional context**

**Comment by kcorey** [comment]
Looking through the Android code, there's already some effort to handle deep links.  I don't yet understand exactly how it is meant to work, but it looks like someone is way ahead of me here.

**Comment by clsource** [comment]
Thanks. Sounds like a nice idea for sharing apps. As long as you have the Jason App you could click a link and see the result. Let's keep this in the TODO list for the new version. May become a core component or similar.

**Comment by clsource** [comment]
I will close this for now. But keep it in the backlog.
