### ISSUE TITLE
How to Establish Session with Traccar API

### ISSUE THREAD

**Issue by andresberejnoi** [jasonelle-archive/jasonelle-v2#77]
First of all, I want to apologize for the lengthy post. This is a spin off question from an issue I opened a few weeks ago. I am looking for help in connecting with the Traccar service using its API and a custom made Android app with Jasonelle. Traccar has its own Android app as well as web client but I want to see if it is possible to make a simple version with Jasonelle. 

**Problem Description**
My problem is that I need to establish a session with a running Traccar server where I already have an account and then keep cookies or something so that future requests are authorized. 

The Traccar API reference page at [https://www.traccar.org/traccar-api/](https://www.traccar.org/traccar-api/) explains that there are two options for authorization:
- Session cookies using the `/api/session` endpoint (documentation [here](https://www.traccar.org/api-reference/#path--session))
- Standard HTTP authorization header

Additionally, there is the option to use a token to create a session, but not for authorization, so I guess it goes back to the first option.

**Standard HTTP Authorization Attempt**
My first approach was to try with standard HTTP authorization since it seemed simpler. According to Wikipedia, I just need to include the something like `Authorization: Basic X3hd$fFHKDSk3KS` in the header of a request. In this case, that random string of letters and numbers would be the base 64 UTF-8 encoding of the string formed by email and password joint by ":" like `email:password`. 

To accomplish this in Jasonellle, I tried using an inline javascript function to encode email and password together (`btoa()`) in a login $action and send it with the header of any requests. 

However, what I was getting was the exact string that I typed, so the javascript code was not being evaluated. In a previous issue I opened I was told that javascript needs to be inside the **templates** section in **head** to be evaluated while mine was just defined as an action in the action registry of the page..  

Here is some action in the way I originally defined it (the javascript function is under `options.header` of the network request):
```
"fetch_location": {
               "type": "$network.request",
               "options": {
                  "url": "http://192.168.0.15/api/positions",
                  "method": "get",
                  "header": {
                     "Authorization": "Basic {{btoa($global.email:$global.password)}}"
                  }
               },
               "success": {
                  "type": "$cache.set",
                  "options": {
                     "items": "{{$jason}}"
                  },
                  "success": {
                     "type": "$util.alert",
                     "options": {
                        "title": "Location fetched",
                        "description": "{{$cache.items.latitude}},{{$cache.items.longitude}}"
                     }
                  }
               },
               "error": {
                  "type": "$util.banner",
                  "options": {
                     "title": "Error Occurred",
                     "description": "Error"
                  }
               }
            }
```

In this example I am assuming that email and password were already set as global variables during login. My login page is simply the one I found in the examples of the Jasonelle documentation, with the network request modified to save variables. 

What I am slightly confused about is the use of templates. How would a template work in this case if my action with the javascript code is defined under `head.actions` and there is no visible data to displayed from this action. 

Additionally, does this mean that from now on all my pages should have the body under **templates** so that I can perform API actions since I need that javascript function executed? If Jasonelle has a built-in action for encoding strings that would also be great. 

**Session Cookies Option**
I guess a more ideal solution would be to use the built-in $session.set function from Jasonelle. However, I don't know exactly know what I am supposed to save. Upon a successful login api call to /api/session, the Traccar server returns a User object with the following properties (the values should be actual values):

```
User = {
    "id": "integer",
    "name": "string",
    'email': "string",
    "readonly": "boolean",
    "administrator": "boolean",
    "map": "string",
    "latitude": "number",
    "longitude": "number",
    "zoom": "integer",
    "password": "string",
    "twelveHourFormat": "boolean",
    "coordinateFormat": "string",
    "disabled": "boolean",
    "expirationTime": "string (date-time) in IS0 8601 format. eg. 1963-11-22T18:30:00Z",

    "deviceLimit": "integer",
    "userLimit": "integer",
    "deviceReadonly": "boolean",
    "limitCommands": "boolean",
    "poiLayer": "string",
    "token": "string",
    "attributes": "object",
}
```
That is the value that I can access from the response, but apparently the server also returns a cookie. I tested this with Postman and on the cookies tab there is a field named "JSESSIONID" with some string of letters as value. 

Is there a way I can access this information? Traccar offers demo servers at [demo.traccar.org](http://demo.traccar.org/) where one can create demo accounts in case someone wants to try it.

**Futher Context**
Ultimately, I am looking for the best way to authenticate to Traccar using the provided API.

**Comment by clsource** [comment]
Hello this line have wrong javascript syntax. This is the correct version that should work and return a result.

`"Authorization": "Basic {{ btoa($global.email + ':' + $global.password) }}"`

`{{ }}` javascript can be used inside the `head.actions` and `templates` sections. If the javascript inside returns an error the engine is programmed to return the operation as string.

For the cookies. Please refer to Example 4 of `$network.request`.

https://jasonelle.com/docs/legacy/actions/#networkrequest


> Dealing with cookies is simple. All you need to do is make the request to create a session. Jason will automatically store the returned cookie, and then attach it to all subsequent requests. Here's an example of signing into a website by making an HTML data_type $network.request call:

```json
{
  "type": "$network.request",
  "options": {
    "url": "https://news.ycombinator.com/login",
    "method": "post",
    "data": {
      "acct": "{{$get.username}}",
      "pw": "{{$get.password}}"
    },
    "data_type": "html"
  },
  "success": {
    "type": "$network.request",
    "options": {
      "url": "https://news.ycombinator.com/saved?id={{$get.username}}",
      "data_type": "html"
    },
    "success": {
      "type": "$render",
      "options": {
        "type": "html"
      }
    }
  }
}
```

**Comment by andresberejnoi** [comment]
Thank you for your help. I checked and I can get certain javascript code to run correctly. For example, the function `JSON.stringify` works in replacement of `btoa`. 

However, I can't get `btoa` to work no matter what I try. I read on some StackOverflow questions that btoa could return an exception if the characters are bigger than 8-bits or something like that. 

In my case I tried setting $global.email to "hello" and $global.password to "hello" as well and I still keep getting the literal string. I also tried a few different functions and variations from answers online to see if I can get it to work, such as `"Authorization" : "Basic {{ btoa(unescape(encodeURIComponent($global.email + ':' + $global.password))) }}"` but with still without success. 

When I try the function from my Chrome's console with the same input I get a correctly encoded string. Maybe there is a difference with the javascript engine version used by Jasonelle.

**Comment by clsource** [comment]
Maybe some version of the engine may not implemented this function.
Try using a polyfill or a native based approach

https://base64.guru/developers/javascript/examples/polyfill

```js
(function () {
  // Do not implement polyfill if browser already support Base64 algorithms
  if (typeof btoa === 'function') {
    return false;
  }

  // A helper that returns Base64 characters and their indices.
  var chars = {
    ascii: function () {
      return 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';
    },
    indices: function () {
      if (!this.cache) {
        this.cache = {};
        var ascii = chars.ascii();

        for (var c = 0; c < ascii.length; c++) {
          var chr = ascii[c];
          this.cache[chr] = c;
        }
      }
      return this.cache;
    }
  };

  /**
   * Binary to ASCII (encode data to Base64)
   * @param {String} data
   * @returns {String}
   */
  window.btoa = function (data) {
    var ascii = chars.ascii(),
      len = data.length - 1,
      i = -1,
      b64 = '';

    while (i < len) {
      var code = data.charCodeAt(++i) << 16 | data.charCodeAt(++i) << 8 | data.charCodeAt(++i);
      b64 += ascii[(code >>> 18) & 63] + ascii[(code >>> 12) & 63] + ascii[(code >>> 6) & 63] + ascii[code & 63];
    }

    var pads = data.length % 3;
    if (pads > 0) {
      b64 = b64.slice(0, pads - 3);

      while (b64.length % 4 !== 0) {
        b64 += '=';
      }
    }

    return b64;
  };

  /**
   * ASCII to binary (decode Base64 to original data)
   * @param {String} b64
   * @returns {String}
   */
  window.atob = function (b64) {
    var indices = chars.indices(),
      pos = b64.indexOf('='),
      padded = pos > -1,
      len = padded ? pos : b64.length,
      i = -1,
      data = '';

    while (i < len) {
      var code = indices[b64[++i]] << 18 | indices[b64[++i]] << 12 | indices[b64[++i]] << 6 | indices[b64[++i]];
      if (code !== 0) {
        data += String.fromCharCode((code >>> 16) & 255, (code >>> 8) & 255, code & 255);
      }
    }

    if (padded) {
      data = data.slice(0, pos - b64.length);
    }

    return data;
  };
})();
```

Also this https://github.com/dchest/tweetnacl-js/issues/44
