### ISSUE TITLE
Documentation for $script.include Probably Outdated

### ISSUE THREAD

**Issue by andresberejnoi** [jasonelle-archive/jasonelle-v2#78]
**Describe the bug**
I was looking at the documentation for $script.include at [https://jasonelle.com/jasonette-old-docs/actions/#scriptinclude](https://jasonelle.com/jasonette-old-docs/actions/#scriptinclude) and it appears to no longer be correct about needing to access imported scripts from $root. 

Documentation says that included scripts through the $script.include functionality will be accessible through `$root`. I just tested this by including CryptoJs script and calling function `$root.CryptoJS.enc.Base64.stringify` which failed but `CryptoJS.enc.Base64.stringify` worked correctly.

I know those docs are supposed to be legacy but I'm just mentioning it in case this is something that was not noticed. Also, if new detailed documentation is available somewhere else could you please share it here? I remember from the Jasonelle website I was able to look at some new examples but I can't find it now.
**To Reproduce**
1. Include JS script with `$script.include`
2. call js function from included library using `$root`

**Expected behavior**
Js code should execute correctly based on old documentation.

**Additional context**
The old documentation is still the best information about Jasonelle (that I know of) so if this is already fixed please disregard this  #post.

**Comment by clsource** [comment]
Thanks. Surely docs needs some love to clarify. I will think a way to improve them and consider this as a todo for an working example 👍

**Comment by andresberejnoi** [comment]
Thank you. I found another unclear part recently but have not opened any issue. Is this the best way to report documentation issues? I don't want to fill this with issues that might be minor.

**Comment by clsource** [comment]
Sure please do create a new issue. That way I could track them 👍 Thanks.
