### ISSUE TITLE
Bottom bar when local file doesn't work as expected or the app crashes

### ISSUE THREAD

**Issue by hubyc** [jasonelle-archive/jasonelle-v2#79]
**Describe the bug**
Bottom bar when local file doesn't work as expected (shows the wrong view) or the app crashes

**Example Jasonette Document URL**
Any bottom bar with "tabs"

**Example Jasonette Document (contents of the file above)**

```json
{
              "tabs": {
                      "style": {
                        "background": "rgba(255,255,255,0.8)",
                        "color:disabled": "#999999",
                        "color": "#000000"
                      },
                      "items": [{
                        "image": "file://img1.png",
                        "text": "text1",
                        "style": {
                          "height": "28"
                        },
                        "url": "file://file1.json"
                      }, {
                        "image": "file://img2.png",
                        "text": "text2",
                        "style": {
                          "height": "28"
                        },
                        "url": "file://file2.json"
                      }, {
                        "image": "file://img3.png",
                        "text": "text3",
                        "style": {
                          "height": "28"
                        },
                        "url": "file://file3.json"
                      }]
              }
}

```

**To Reproduce**
1. Make all the files are local
2. Create bottom bar with tabs
3. When the app is running then:
a) switching to another tab crashes the app
b) OR switching between tabs is messy (clicking on tab 2 shows view for tab 1; must tap it again to get view for tab 2; then switching to tab 1 is similar - it show again view 2 and only on second tap, show the correct view 1.

**Expected behavior**
Tabs should be associated with the respective views and the app shouldn't crash.

**Smartphone (please complete the following information):**
 - Device: Iphone X
 - OS: iOS 13.3

**Compilation**:
 - Tested on Jason App?: No, it's offline
 - Version v2 of jasonette, compiled with xcode 11.3

**Comment by clsource** [comment]
Thanks. This will be considered in the next version :)
