### ISSUE TITLE
Debug notice when there is no network connection

### ISSUE THREAD

**Issue by hubyc** [jasonelle-archive/jasonelle-v2#80]
**Describe the bug**
Debug notice when there is no network connection

**To Reproduce**
1. Switch off the internet connection
2. Start the app
The error screen appears but at the same time a pop up with title "Debug" appear saying there is no network connection

**Expected behavior**
The popup shouldn't appear, there is a dedicated screen for errors (which appears ok)

**Smartphone (please complete the following information):**
 - Device: Iphone X
 - OS: 13.3

**Comment by clsource** [comment]
Thanks. This will be considered in the next version :)
