### ISSUE TITLE
'SBJson/SBJson4Writer.h' file not found

### ISSUE THREAD

**Issue by mdings** [jasonelle-archive/jasonelle-v2#82]
I'm trying to run Jasonelle from my iPhone but I'm stuck with Xcode giving me an error.

Steps to reproduce:
- Download the latest version for iOS (https://github.com/jasonelle/jasonelle/releases)
- Unzip and open app/Jasonette.xcodeproj
- Hit play to run on iPhone  <img width="322" alt="Schermafbeelding 2020-02-19 om 10 48 09" src="https://user-images.githubusercontent.com/1887262/74822379-52f5be00-5305-11ea-8108-4cacf6265c1f.png">
- Find yourself stuck at the following error message: 'SBJson/SBJson4Writer.h' file not found
<img width="400" alt="Schermafbeelding 2020-02-19 om 10 48 46" src="https://user-images.githubusercontent.com/1887262/74822438-69037e80-5305-11ea-8603-900cc644aea2.png">

I'm running Xcode Version 11.3.1 (11C504)

Any ideas how to fix this?

**Comment by mdings** [comment]
Never mind. I just found out that I have to run the setup instead of opening the project directly in XCode 🤗

**Comment by clsource** [comment]
xdd cool 👍

**Comment by mdings** [comment]
I have the same issue with the latest version (2.1) for iOS. But now the setup is gone 😀

**Comment by clsource** [comment]
Pod install usually does the trick 😀
