### ISSUE TITLE
Jasonette.xcworkspace throws error

### ISSUE THREAD

**Issue by manking109** [jasonelle-archive/jasonelle-v2#83]
When I upload the IOS app to excode using Jasonette.xcworkspace and run the app
jasonette-ios-master/xcode/Jasonette/Core/Jason/jason.h

#if DEBUG
#include <FLEX/FLEX.h>
#endif
can not find flex.h file 

If I load the IOS app to xcode using  Jasonette.xcodeproj and run the app
jasonette-ios-master/xcode/Jasonette/Core/Jason/jason.h

the xcode cant seem to find several of the PODS i saw at lest 3 maybe 4 pod error

**Comment by clsource** [comment]
This maybe due to the pods being not installed. Please ensure that Pods are installed
executing
`pod install` inside the xcode directory.

https://cocoapods.org/

**Comment by manking109** [comment]
that worked thanks
