### ISSUE TITLE
May I know is there any "visual tools" that will generate the JSON for jasonelle like https://flutterstudio.app/ for flutter?

### ISSUE THREAD

**Issue by DaFrik** [jasonelle-archive/jasonelle-v2#91]
as titled. 

I envision it will be great (and should not be rocket science) to have a visual editor (able to see the list of "Assets" that could be use and have "blocks of code snippets" to drag and drop) to help "compile" the JSON that works with jasonelle. I suspect there might already be tools like that out there. I just want to ask and don't want to reinvent the wheel.

**Comment by clsource** [comment]
Hello there is an ongoing project by the community to create a visual editor 👍 
The main dev is https://github.com/vini-brito 💯
