### ISSUE TITLE
"pod install" or "pod update" results in "Cocoapods could not find compatible versions" pod errors for version 2.0

### ISSUE THREAD

**Issue by atlowell-smpl** [jasonelle-archive/jasonelle-v2#93]
When running "pod install" or "pod update" on a repository using iOS version 2.0, the command fails with a group of error messages taking the forms of:

```Cocoapods could not find compatible versions for pod "AFNetworking"```
```Cocoapods could not find compatible versions for pod "AFNetworking/NSUrlConnection"```

The dependencies missing are as follows:
```AFNetworking (~> 2.2)
AFNetworking/NSURLConnection (~> 2.2)
AFNetworking/NSURLSession (= 4.0.1)
AFNetworking/NSURLSession (~> 3.0)
```

The AFNetworking pod is installed using the following command in the Podfile:
```  pod 'AFNetworking', :git => 'https://github.com/jasonelle/ios-pod-afnetworking.git', :branch => 'jasonelle'```

The repository in question was updated to version 4 (then 4.0.1) several months ago. Interestingly enough, changing the Podfile to use a a commit from right before the version 4 update causes the error to go away and the app to work correctly:
```  pod 'AFNetworking', :git => 'https://github.com/jasonelle/ios-pod-afnetworking.git', :commit => 'e24d494eff2e4bcfc7f31b5be1c7d9ac18fde722'```

It seems that the issue is that version 2.0 of Jasonelle requires AFNetworking 2 and 3. Updating the repository to version 4 caused the pod install to fail for older versions. This is likely to continue to happen as other pods are updated. I can see three potential solutions moving forward:

1. Ensure every pod repository supports backwards compatibility for older versions. This seems impractical, especially since pod updates are often forked directly from their main pod repository, and thus we would be dependent on pod creators to implement said backwards compatibility for us (or do it ourselves).
2. Update older versions of Jasonelle periodically to support updates to pod frameworks.
3. Maintain a separate branch of each pod repository for use with each jasonelle version. The version 2.0 AFNetworking branch therefore wouldn't be updated to version 4, unless jasonelle version 2.0 was later updated to use AFNetworking 4.

**Comment by clsource** [comment]
Thanks 👍 .
Yes, you are right. A little fix to pinpoint the correct commit versions should be made in order to avoid this problem in the future. Is better for a framework to have exact version numbers, in this case, exact commit hashes to avoid future conflicts.

The procedure would be to correct the Podfile in version 2.0 with all the working pods with specific commit hashes. Every new official release should change the `:branch => 'jasonelle'` to the current commit hash at the time of release.
